# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngrpc.proto\"\x1e\n\x06\x61\x64\x64Msg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x0brawImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"%\n\rdotProductMsg\x12\t\n\x01\x61\x18\x01 \x03(\x02\x12\t\n\x01\x62\x18\x02 \x03(\x02\"\x1b\n\x0cjsonImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\t\"\x17\n\x08\x61\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"%\n\x0f\x64otProductReply\x12\x12\n\ndotproduct\x18\x01 \x01(\x02\"+\n\nimageReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32\"\n\x03\x61\x64\x64\x12\x1b\n\x03\x61\x64\x64\x12\x07.addMsg\x1a\t.addReply\"\x00\x32\x33\n\x08rawImage\x12\'\n\x08rawImage\x12\x0c.rawImageMsg\x1a\x0b.imageReply\"\x00\x32>\n\ndotProduct\x12\x30\n\ndotProduct\x12\x0e.dotProductMsg\x1a\x10.dotProductReply\"\x00\x32\x36\n\tjsonImage\x12)\n\tjsonImage\x12\r.jsonImageMsg\x1a\x0b.imageReply\"\x00\x62\x06proto3')



_ADDMSG = DESCRIPTOR.message_types_by_name['addMsg']
_RAWIMAGEMSG = DESCRIPTOR.message_types_by_name['rawImageMsg']
_DOTPRODUCTMSG = DESCRIPTOR.message_types_by_name['dotProductMsg']
_JSONIMAGEMSG = DESCRIPTOR.message_types_by_name['jsonImageMsg']
_ADDREPLY = DESCRIPTOR.message_types_by_name['addReply']
_DOTPRODUCTREPLY = DESCRIPTOR.message_types_by_name['dotProductReply']
_IMAGEREPLY = DESCRIPTOR.message_types_by_name['imageReply']
addMsg = _reflection.GeneratedProtocolMessageType('addMsg', (_message.Message,), {
  'DESCRIPTOR' : _ADDMSG,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:addMsg)
  })
_sym_db.RegisterMessage(addMsg)

rawImageMsg = _reflection.GeneratedProtocolMessageType('rawImageMsg', (_message.Message,), {
  'DESCRIPTOR' : _RAWIMAGEMSG,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:rawImageMsg)
  })
_sym_db.RegisterMessage(rawImageMsg)

dotProductMsg = _reflection.GeneratedProtocolMessageType('dotProductMsg', (_message.Message,), {
  'DESCRIPTOR' : _DOTPRODUCTMSG,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:dotProductMsg)
  })
_sym_db.RegisterMessage(dotProductMsg)

jsonImageMsg = _reflection.GeneratedProtocolMessageType('jsonImageMsg', (_message.Message,), {
  'DESCRIPTOR' : _JSONIMAGEMSG,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:jsonImageMsg)
  })
_sym_db.RegisterMessage(jsonImageMsg)

addReply = _reflection.GeneratedProtocolMessageType('addReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDREPLY,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:addReply)
  })
_sym_db.RegisterMessage(addReply)

dotProductReply = _reflection.GeneratedProtocolMessageType('dotProductReply', (_message.Message,), {
  'DESCRIPTOR' : _DOTPRODUCTREPLY,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:dotProductReply)
  })
_sym_db.RegisterMessage(dotProductReply)

imageReply = _reflection.GeneratedProtocolMessageType('imageReply', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREPLY,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:imageReply)
  })
_sym_db.RegisterMessage(imageReply)

_ADD = DESCRIPTOR.services_by_name['add']
_RAWIMAGE = DESCRIPTOR.services_by_name['rawImage']
_DOTPRODUCT = DESCRIPTOR.services_by_name['dotProduct']
_JSONIMAGE = DESCRIPTOR.services_by_name['jsonImage']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDMSG._serialized_start=14
  _ADDMSG._serialized_end=44
  _RAWIMAGEMSG._serialized_start=46
  _RAWIMAGEMSG._serialized_end=72
  _DOTPRODUCTMSG._serialized_start=74
  _DOTPRODUCTMSG._serialized_end=111
  _JSONIMAGEMSG._serialized_start=113
  _JSONIMAGEMSG._serialized_end=140
  _ADDREPLY._serialized_start=142
  _ADDREPLY._serialized_end=165
  _DOTPRODUCTREPLY._serialized_start=167
  _DOTPRODUCTREPLY._serialized_end=204
  _IMAGEREPLY._serialized_start=206
  _IMAGEREPLY._serialized_end=249
  _ADD._serialized_start=251
  _ADD._serialized_end=285
  _RAWIMAGE._serialized_start=287
  _RAWIMAGE._serialized_end=338
  _DOTPRODUCT._serialized_start=340
  _DOTPRODUCT._serialized_end=402
  _JSONIMAGE._serialized_start=404
  _JSONIMAGE._serialized_end=458
# @@protoc_insertion_point(module_scope)
